# 1 K8's version - apiVersion - v1
apiVersion: v1

# 2 Type of K8's Component - Secret
kind: Secret

# 3 Metadata of K8's
metadata:
  name: secret1
  labels:
    app: app-secret1

type: Opaque

# 4 Specification (data) of your app
data:
  # Key1: value1
  # username: rohit
  # password: rohit@1234
  username: cm9oaXQ=
  password: cm9oaXRAMTIzNA==
  